// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm7nuP7b6EPk5XX4Yd_pWGjiOUEwIeUlk',
    appId: '1:166852986555:web:e6361a4517ff5a6c7b8b9e',
    messagingSenderId: '166852986555',
    projectId: 'movie-app-20892',
    authDomain: 'movie-app-20892.firebaseapp.com',
    storageBucket: 'movie-app-20892.appspot.com',
    measurementId: 'G-9CG7VHH12Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA16j7Cjd_Ashm3AwCetGelKRu4i12oHs',
    appId: '1:166852986555:android:1f038bc6411ef0127b8b9e',
    messagingSenderId: '166852986555',
    projectId: 'movie-app-20892',
    storageBucket: 'movie-app-20892.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCy2kf8cGRuhQyvSJOAnDySCTCyMPLrJ0',
    appId: '1:166852986555:ios:c58463568cf056427b8b9e',
    messagingSenderId: '166852986555',
    projectId: 'movie-app-20892',
    storageBucket: 'movie-app-20892.appspot.com',
    androidClientId: '166852986555-c8vnpc4coi3jjh1pb0c38vahgs54ve7b.apps.googleusercontent.com',
    iosClientId: '166852986555-qh1q3rkubr2bj62b65t9mjm7tevrj0oa.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );
}
